# Usar una imagen base de Go 1.21.0
FROM golang:1.21.0-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo go.mod y go.sum
COPY go.mod go.sum ./

# Descargar las dependencias
RUN go mod download

# Copiar el código fuente
COPY . .

# Copiar el archivo de configuración
COPY app.env ./

# Construir la aplicación
RUN go build -o order-service

# Exponer el puerto en el que la aplicación escuchará
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["./order-service"]
