name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  check_approver:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR Approvals
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requiredApprover = "JuanGuevara90";

            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedBy = reviews
              .filter(review => review.state === "APPROVED")
              .map(review => review.user.login);

            if (!approvedBy.includes(requiredApprover)) {
              core.setFailed(`Solo ${requiredApprover} puede aprobar este PR.`);

  build_and_push:
    needs: check_approver
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [order-service, order-tracking, order-history]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for ${{ matrix.service }}
        run: docker build -t malquinaguirre98/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Push Docker image for ${{ matrix.service }}
        run: docker push malquinaguirre98/${{ matrix.service }}:latest
